### ISSUE TITLE
Comet Run not Converting SQT Files

### ISSUE THREAD

**Issue by gmhernandezneu** [pwilmart/PAW_pipeline#2]
Hello Phil,

I am running into trouble running the Comet command. After I hit run, I immediately receive the error as pictured below in my idle console "Warning - folder does not contain any SQT files." How do I remedy this problem? Could it stem from how I set up the program command? Thank you for your help!

![image](https://user-images.githubusercontent.com/66029685/83052234-06fd9800-a01d-11ea-82f8-7e036495c00c.png)

Best,
Gabby

**Comment by pwilmart** [comment]
Hi Gabby,
Look at this and see if the Comet command is set up correctly. The error occurs when each Comet command fails. The launching a Windows command shell kind of happens in the background and I do not have a mechanism in place to capture any of the Comet error messages and pass them on in the GUI. All of the failed Comet commands can happen quickly, then there are no SQT output files, and you get the error message. Let me know how it goes.
Cheers,
Phil

**Comment by pwilmart** [comment]
oops, here is the link: https://github.com/pwilmart/PAW_pipeline/blob/master/docs/Comet.md

**Comment by gmhernandezneu** [comment]
Hi Phil,
I re-setup the Comet command and it worked. Thank you for your help!
Best, 
Gabby
